### ISSUE TITLE
versioneye.properties file should allow specification of baseUrl (and, perhaps, all properties).

### ISSUE THREAD

**Issue by Comet-Symphony** [versioneye/versioneye_maven_plugin#65]
The versioneye.properties file can store the apiKey, so that one doesn't have to modify the pon.xml.
When using the Enterprise VersionEye code, the pom.xml MUST be modified to specify baseUrl.

Ideally, all the configuration parameters should be specifiable in the versioneye.properties file, so that one doesn't have to modify every project's pom.xml (at least to specify baseUrl).

> The VersionEye Maven Plugin has many configuration options.
> 
>       <plugin>
>         <groupId>com.versioneye</groupId>
>         <artifactId>versioneye-maven-plugin</artifactId>
>         <version>3.10.2</version>
>         <configuration>
>           <projectId>544d0ff9512592562c000003</projectId>
>           
>           
>           
>           
>           
>           
>           
>           
>           
>           
>           
>           
>           
>           
>           
>           
>           
>           
>           
>           
>         </configuration>
>       </plugin>

**Comment by reiz** [comment]
@Comet-Symphony That makes sense. That's a good feature request :)

**Comment by reiz** [comment]
@Comet-Symphony I close this ticket because it's implemented now and I just pushed it to Maven central. In ~ 1 hour you can pull down version 3.11.0 from Maven central. With that version you can even store the base URL in an ENV variable. The plugin will check the ENV variable `VERSIONEYE_BASE_URL` first, before it looks in the properties files.
